### PR TITLE
Invite written, changes to replies

### PR DESCRIPTION
**Pull request by jongoad**
- Having some issues with double join attempts
- Need to update many more replies

### CODE REVIEW

**Review by Spawnzer — APPROVED** [review]
lgtm

**Review by oddtiming — DISMISSED** [review]
All changes seem fine to me. Still need to debug double printing for joining a channel you'd been invited to

**Review by oddtiming — APPROVED** [review]
Still good after conflict resolution!

**Review by Spawnzer — APPROVED** [review]
lgtm

**Pull request merged**
