### PR TITLE
Commands

### PR DESCRIPTION
**Pull request by Spawnzer**

### CODE REVIEW

**Review by oddtiming — APPROVED** [review]
There is a segfault in this build (trying to access a channel that doesn't exist), but is fixed by a subsequent PR

**Review by jongoad — APPROVED** [review]
Nothing to add

**Review by jongoad — APPROVED** [review]
Merge conflicts resolved, good to merge

**Review by oddtiming — APPROVED** [review]
Fixed merge conflicts in PR #11

**Pull request merged**
